-- 
-- --local function opts(desc)
-- --  return { desc = "nvim-tree: " .. desc, noremap = true, silent = true, nowait = true }
-- --end
-- --
-- --
-- local function open_nvim_tree()
--   require("nvim-tree.api").tree.open()
-- end
-- 
-- vim.api.nvim_create_autocmd({ "VimEnter" }, { callback = open_nvim_tree })
-- 
-- 
-- return {
--   "nvim-tree/nvim-tree.lua",
--   lazy = false,
--   dependencies = {
--     "nvim-tree/nvim-web-devicons",
--   },
--   config = function()
--     require("nvim-tree").setup({
--         update_focused_file = {
--           enable = true,
--         }})
--     -- Keymaps after setup
--     vim.keymap.set('n', '<C-t>', require("nvim-tree.api").tree.change_root_to_parent)
--     vim.keymap.set('n', '?', require("nvim-tree.api").tree.toggle_help)
--     vim.keymap.set('n', '<leader>e', require("nvim-tree.api").tree.toggle)
--   end,
-- }
--
return {}
